name: duiv-web

volumes:
  media:
    driver: local
  pgdata:
    driver: local

networks:
  app_network:
    driver: bridge

services:
  django:
    image: cr.yandex/${YC_REGISTRY}/django-service:latest
    ports:
      - 8000:8000
    volumes:
      - media:/media
    env_file:
      - ./.env
    networks:
      - app_network
    depends_on:
      - postgres-db
      - redis

  postgres-db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - app_network
    restart: always
    

  celery:
    image: cr.yandex/${YC_REGISTRY}/celery-service:latest
    volumes:
      - media:/media
      - ./logs/celery:/app/logs
    env_file:
      - ./.env
    networks:
      - app_network
    depends_on:
      - django
      - redis
      - postgres-db

  redis:
    image: redis:5-alpine
    networks:
      - app_network

  practical-rife:
    image: cr.yandex/${YC_REGISTRY}/rife-service:latest
    ports:
      - 5000:5000
    volumes:
      - media:/media
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    networks:
        - app_network
    runtime: nvidia
  
  esrgan:
    image: cr.yandex/${YC_REGISTRY}/esrgan-service:latest
    ports:
      - 5001:5001
    volumes:
      - media:/media
    environment:
        - NVIDIA_VISIBLE_DEVICES=all
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    networks:
        - app_network
    runtime: nvidia