volumes:
  media:
    driver: local
  pgdata:
    driver: local

networks:
  app_network:
    driver: bridge

services:
  django:
    image: cr.yandex/${YC_REGISTRY}/django-service:latest
    ports:
      - 8000:8000
    env_file:
      - ./.env
    volumes:
      - media:/media
    networks:
      - app_network
    depends_on:
      - postgres-db
      - redis
    restart: always

  postgres-db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    networks:
      - app_network
    restart: always

  celery:
    image: cr.yandex/${YC_REGISTRY}/celery-service:latest
    env_file:
      - ./.env
    volumes:
      - media:/media
    networks:
      - app_network
    depends_on:
      - django
      - redis
    restart: always

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
    networks:
      - app_network
    restart: always

  practical-rife:
    image: cr.yandex/${YC_REGISTRY}/rife-service:latest
    ports:
      - 5000:5000
    volumes:
      - media:/media
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - app_network
    restart: always

  esrgan:
    image: cr.yandex/${YC_REGISTRY}/esrgan-service:latest
    ports:
      - 5001:5001
    volumes:
      - media:/media
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - app_network
    restart: always
