version: "3.9"

volumes:
  media:
    driver: local
  pgdata:
    driver: local

networks:
  app_network:
    driver: bridge

services:
  django:
    image: cr.yandex/${YC_REGISTRY}/django-service:latest
    env_file:
      - ./.env
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres-db
      - redis
    restart: always
    networks:
      - app_network

  postgres-db:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_network

  celery:
    image: cr.yandex/${YC_REGISTRY}/celery-service:latest
    env_file:
      - ./.env
    volumes:
      - media:/media
    depends_on:
      - django
      - redis
    restart: always
    networks:
      - app_network

  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app_network

  practical-rife:
    image: cr.yandex/${YC_REGISTRY}/rife-service:latest
    command: python3 /app/server_interpolation.py
    volumes:
      - media:/media
    ports:
      - "5000:5000"
    restart: always
    networks:
      - app_network

  upscale:
    image: cr.yandex/${YC_REGISTRY}/upscale-service:latest
    command: python3 /app/server_upscale.py
    volumes:
      - media:/media
    ports:
      - "5001:5001"
    restart: always
    networks:
      - app_network
