name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Yandex Cloud Container Registry
        run: |
          echo ${{ secrets.YC_OAUTH }}| docker login \
            --username oauth \
            --password-stdin \
            cr.yandex

      - name: Build and push Django image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY }}/django-service:latest ./builds/django
          docker push cr.yandex/${{ secrets.YC_REGISTRY }}/django-service:latest

      - name: Build and push Celery image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY }}/celery-service:latest ./builds
          docker push cr.yandex/${{ secrets.YC_REGISTRY }}/celery-service:latest

      - name: Build and push RIFE image
        run: |
          ( while true; do
                  echo "::notice::build & push rife image ⏳ $(date +%T)"
                  sleep 45
              done ) & KEEP_PID=$!

          docker build -t cr.yandex/${{ secrets.YC_REGISTRY }}/rife-service:latest ./builds/rife
          docker push cr.yandex/${{ secrets.YC_REGISTRY }}/rife-service:latest

          kill $KEEP_PID

      - name: Build and push Real-ESRGAN image
        run: |
          ( while true; do
                  echo "::notice::build & push real-esrgan image ⏳ $(date +%T)"
                  sleep 45
              done ) & KEEP_PID=$!

          docker build -t cr.yandex/${{ secrets.YC_REGISTRY }}/upscale-service:latest ./builds/upscale
          docker push cr.yandex/${{ secrets.YC_REGISTRY }}/upscale-service:latest

          kill $KEEP_PID

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Docker login & pull images on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -euo pipefail
            echo "${{ secrets.YC_OAUTH }}" | docker login --username oauth --password-stdin cr.yandex

            ( while true; do
                  echo "::notice::pulling images ⏳ $(date +%T)"
                  sleep 45
              done ) & KEEP_PID=$!

            docker pull cr.yandex/${{ secrets.YC_REGISTRY }}/rife-service:latest
            docker pull cr.yandex/${{ secrets.YC_REGISTRY }}/django-service:latest
            docker pull cr.yandex/${{ secrets.YC_REGISTRY }}/celery-service:latest
            docker pull cr.yandex/${{ secrets.YC_REGISTRY }}/upscale-service:latest
            kill $KEEP_PID
          EOF

      - name: Restart containers on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -ex
            echo "Restarting containers..."
            cd ~/deploy/app
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d
            docker image prune -f
          EOF