name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  push-images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Django
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/django-service:latest ./builds/django
          docker push ${{ secrets.DOCKER_USERNAME }}/django-service:latest

      - name: Build and push RIFE
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rife-service:latest ./builds/rife
          docker push ${{ secrets.DOCKER_USERNAME }}/rife-service:latest

      - name: Build and push Upscale
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/upscale-service:latest ./builds/upscale
          docker push ${{ secrets.DOCKER_USERNAME }}/upscale-service:latest