name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Yandex Cloud Container Registry
        run: |
          echo ${{ secrets.YC_OAUTH }}| docker login \
            --username oauth \
            --password-stdin \
            cr.yandex

      - name: Build and push Django image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY }}/django-service:latest ./builds/django
          docker push cr.yandex/${{ secrets.YC_REGISTRY }}/django-service:latest

      - name: Build and push RIFE image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY }}/rife-service:latest ./builds/rife
          docker push cr.yandex/${{ secrets.YC_REGISTRY }}/rife-service:latest

      - name: Build and push Upscale image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY }}/upscale-service:latest ./builds/upscale
          docker push cr.yandex/${{ secrets.YC_REGISTRY }}/upscale-service:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Pull and restart services on remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -ex

            echo "Pulling images..."
            docker pull cr.yandex/${{ secrets.YC_REGISTRY }}/django-service:latest
            docker pull cr.yandex/${{ secrets.YC_REGISTRY }}/rife-service:latest
            docker pull cr.yandex/${{ secrets.YC_REGISTRY }}/upscale-service:latest

            echo "Injecting .env..."
            export SECRET_KEY="${{ secrets.SECRET_KEY }}"

            echo "Restarting containers..."
            cd ~/deploy/app
            docker-compose down
            docker-compose -f docker-compose.prod.yml up -d
          EOF