name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: UIDataBase
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 111
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379

    env:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_DB: UIDataBase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        working-directory: builds/django
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Run tests
        working-directory: builds/django
        run: |
          python manage.py migrate

      - name: Lint and type-check
        working-directory: builds/django
        continue-on-error: true
        run: |
          black --check .
          pylint .

      - name: Build Django image
        run: docker build -t django-service ./builds/django

      - name: Build RIFE image
        run: docker build -t rife-service ./builds/rife

      - name: Build Upscale image
        run: docker build -t upscale-service ./builds/upscale
